pipeline {
    agent any

    environment {
        REGISTRY = "docker.io/miatrika05/ticklab"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        DEPLOY_USER = "root"
        DEPLOY_HOST = "192.168.100.101"
        DEPLOY_PATH = "/var/www/ticklab"
    }

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '20'))
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Build') {
            steps {
                script {
                    load "${env.WORKSPACE}/jenkins/stages/build.groovy"
                }
            }
        }

        stage('Test & Quality') {
            parallel {
                stage('Unit Tests') {
                    steps {
                        ansiColor('xterm') {
                            script { load "${env.WORKSPACE}/jenkins/stages/test.groovy" }
                        }
                    }
                }
                stage('Static Analysis') {
                    steps {
                        ansiColor('xterm') {
                            script { load "${env.WORKSPACE}/jenkins/stages/qa.groovy" }
                        }
                    }
                }
                stage('Security Scan') {
                    steps {
                        ansiColor('xterm') {
                            script { load "${env.WORKSPACE}/jenkins/stages/security.groovy" }
                        }
                    }
                }
            }
        }

        stage('Package & Push') {
            steps {
                ansiColor('xterm') {
                    script {
                        sh "docker build -t ${REGISTRY}:${IMAGE_TAG} ."
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                            sh 'echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin'
                            sh "docker tag ${REGISTRY}:${IMAGE_TAG} ${REGISTRY}:latest"
                            // sh "docker push ${REGISTRY}:${IMAGE_TAG} || echo 'Push failed'"
                            // sh "docker push ${REGISTRY}:latest"
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                ansiColor('xterm') {
                    script { load 'jenkins/stages/deploy.groovy' }
                }
            }
        }
    }

    post {
        success { echo "✅ Pipeline completed successfully." }
        failure { echo "❌ Pipeline failed — check logs." }
        always {
            sh 'docker container prune -f || true'
            sh 'docker image prune -f || true'
        }
    }
}
