pipeline {
    agent any

    environment {
        REGISTRY = "docker.io/miatrika05/ticklab"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        DEPLOY_USER = "miatrika"
        DEPLOY_HOST = "192.168.100.50"
        DEPLOY_PATH = "/var/www/ticklab"
        APP_PORT = "443"
        DB_PASSWORD = credentials('ticklab-db-password')
        SONAR_TOKEN = credentials('sonarqube-token')
    }

    triggers {
        pollSCM('H/2 * * * *')
    }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '20'))
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout')  {
            steps {
                sshagent(['github-ssh']) {
                    sh 'git fetch --tags --force --progress --prune origin main'
                }
            }
        }

        stage('Load Ensure DB') {
            steps { script { load "${env.WORKSPACE}/jenkins/stages/ensure-db.groovy" } }
        }

        stage('Build') {
            steps { script { load "${env.WORKSPACE}/jenkins/stages/build.groovy" } }
        }

        stage('Test & Quality') {
            parallel {
                stage('Unit Tests') {
                    steps { ansiColor('xterm') { script { load "${env.WORKSPACE}/jenkins/stages/test.groovy" } } }
                }
                stage('Static Analysis') {
                    steps { ansiColor('xterm') { script { load "${env.WORKSPACE}/jenkins/stages/qa.groovy" } } }
                }
                stage('Security Scan') {
                    steps { ansiColor('xterm') { script { load "${env.WORKSPACE}/jenkins/stages/security.groovy" } } }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    load "${env.WORKSPACE}/jenkins/stages/sonarqube.groovy"
                }
            }
        }

        stage('Test Credentials') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'U', passwordVariable: 'P')]) {
                        echo "✅ Docker credentials OK for ${U}"
                    }
                }
            }
        }

        stage('Package & Push') {
            steps { script { load "${env.WORKSPACE}/jenkins/stages/package_push.groovy" } }
        }

        stage('Build & Push Nginx') {
            steps { script { load "${env.WORKSPACE}/jenkins/stages/build_push_nginx.groovy" } }
        }

        stage('Deploy') {
            steps { script { load "${env.WORKSPACE}/jenkins/stages/deploy.groovy" } }
        }
    }

    post {
        success { echo "✅ Pipeline completed successfully." }
        failure { echo "❌ Pipeline failed — check logs." }
        always {
            sh 'docker container prune -f || true'
            sh 'docker image prune -f || true'
        }
    }
}
